### ISSUE TITLE
NullReferenceException thrown when using PutObjectAsync 

### ISSUE THREAD

**Issue by marwa-elfakir-logi** [minio/minio-dotnet#1128]
When uploading JSON data as an object to a bucket on Minio using the PutObjectAsync method => it works well in our local develoment setup and it does in fact upload the files successfully.
But a NullReferenceException is intermittently thrown in the client's server environment,

We're using version 6.0.0 of the package.

We're currently investigating potential differences or configurations that could lead to this exception. We checked the access key policy through the client's minio console and it looks well => The upload to the bucket is allowed along with other operations. We're somewhat stuck and uncertain about which path to investigate. Could it be linked to the client's bucket configuration since it's different from ours ? if yes then what exactly should we check ? if not then what could be triggering the error ? 
Any insights or suggestions for resolution would be greatly appreciated.

Our function that calls PutObject:

![image](https://github.com/minio/minio-dotnet/assets/171275881/f37a5caf-25b8-47cd-9133-40575a8754f6)

Stack Trace:

`System.NullReferenceException: Object reference not set to an instance of an object.
   at Minio.MinioClient.ParseErrorFromContent(ResponseResult response)
   at Minio.MinioClient.ParseError(ResponseResult response)
   at Minio.Handlers.DefaultErrorHandler.Handle(ResponseResult response)
   at Minio.RequestExtensions.HandleIfErrorResponse(IMinioClient minioClient, ResponseResult response, IEnumerable`1 handlers, DateTime startTime)
   at Minio.RequestExtensions.ExecuteTaskCoreAsync(IMinioClient minioClient, IEnumerable`1 errorHandlers, HttpRequestMessageBuilder requestMessageBuilder, Boolean isSts, CancellationToken cancellationToken)
   at Minio.RequestExtensions.<>cDisplayClass2_0.<<ExecuteTaskAsync>b0>d.MoveNext()
   at Minio.MinioClient.PutObjectSinglePartAsync(PutObjectArgs args, CancellationToken cancellationToken)
   at Minio.MinioClient.PutObjectAsync(PutObjectArgs args, CancellationToken cancellationToken)`

Thank you for your assistance in resolving this issue.

**Comment by rbauduin** [comment]
In the hope this helps future readers, I had this problem when I used inexisting access and secret keys.
