### ISSUE TITLE
Using CopyToAsync when copying stream from GetObjectAsync

### ISSUE THREAD

**Issue by cklogs** [minio/minio-dotnet#338]
Hello.

I want to follow best practices and use async when copying from the Stream to MemoryStream in the below code block, but the following will occasionally hard crash my application with the following error:

```
Unhandled Exception: System.IO.IOException: Unable to read data from the transport connection: The I/O operation has been aborted because of either a thread exit or an application request. ---> System.Net.Sockets.SocketException: The I/O operation has been aborted because of either a thread exit or an application request
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.GetResult(Int16 token)
   at System.Net.Http.HttpConnection.FillAsync()
   at System.Net.Http.HttpConnection.CopyToExactLengthAsync(Stream destination, UInt64 length, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnection.ContentLengthReadStream.CompleteCopyToAsync(Task copyTask, CancellationToken cancellationToken)
   at Hyperview.Manager.AssetUtils.FileStorage.MinioService.<>c__DisplayClass3_0.<<GetImageByteArrayAsync>b__0>d.MoveNext() in C:\Projects\manager\src\AssetUtils\FileStorage\MinioService.cs:line 26
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ThreadPoolWorkQueue.Dispatch()

Unhandled Exception: System.IO.IOException: Unable to read data from the transport connection: The I/O operation has been aborted because of either a thread exit or an application request. ---> System.Net.Sockets.SocketException: The I/O operation has been aborted because of either a thread exit or an application request
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.GetResult(Int16 token)
   at System.Net.Http.HttpConnection.FillAsync()
   at System.Net.Http.HttpConnection.CopyToExactLengthAsync(Stream destination, UInt64 length, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnection.ContentLengthReadStream.CompleteCopyToAsync(Task copyTask, CancellationToken cancellationToken)
   at Hyperview.Manager.AssetUtils.FileStorage.MinioService.<>c__DisplayClass3_0.<<GetImageByteArrayAsync>b__0>d.MoveNext() in C:\Projects\manager\src\AssetUtils\FileStorage\MinioService.cs:line 26
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
```

My ideal solution.

```
try {
	await minioObjectOperationsClient.GetObjectAsync(bucketName, imageId.ToString(), async (stream) => {
			using (var responseStream = new MemoryStream()) {
				await stream.CopyToAsync(responseStream).ConfigureAwait(false);
				image = responseStream.ToArray();
			}
		}).ConfigureAwait(false);

		return image;
	} catch (Exception exception) {
		throw new Exception($"GetImageByteArrayAsync OnError. ObjectId: {imageId}, Bucket: {bucketName}", exception);
	}
```

What I'm doing right now.

```
try {
	await minioObjectOperationsClient.GetObjectAsync(bucketName, imageId.ToString(), (stream) => {
		using (var responseStream = new MemoryStream()) {
			stream.CopyTo(responseStream);
			image = responseStream.ToArray();
		}
	}).ConfigureAwait(false);

	return image;
} catch (Exception exception) {
	throw new Exception($"GetImageByteArrayAsync OnError. ObjectId: {imageId}, Bucket: {bucketName}", exception);
}
````

I noticed also that none of the example code used CopyToAsync and that perhaps this is required.

Please let me know how best to proceed.

Thank you.

**Comment by kannappanr** [comment]
@cklogs We will take a look at this and get back to you.

**Comment by cklogs** [comment]
@kannappanr Thanks for the speedy response!

**Comment by poornas** [comment]
Thanks for raising this issue @cklogs, the socket seems to be closing here before the response is fully read for the example snippet posted above. 

If the underlying GetObjectAsync implementation is changed to use stream.CopyToAsync() - it causes ArgumentOutOfRangeException unless the CopyToAsync(stream, streamsize) variant  is specified both in the API call and the invocation on the client side.  You would be better off using the working example - minio client sdk abstracts the HEAD call needed to compute size of the object within the GetObjectAsync implementation. If the minio-dotnet sdk were changed to the stream.CopyToAsync(stream, streamsize) call, the client would also have to issue a StatObjectAsync call to compute size prior to fetching an object and pass this size in the CopyToAsync call.
```
Unhandled Exception: System.ArgumentOutOfRangeException: Non-negative number required.
Parameter name: count
   at System.Buffer.BlockCopy(Array src, Int32 srcOffset, Array dst, Int32 dstOffset, Int32 count)
   at System.Net.Http.HttpConnection.FillAsync()
   at System.Net.Http.HttpConnection.CopyToExactLengthAsync(Stream destination, UInt64 length, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnection.ContentLengthReadStream.CompleteCopyToAsync(Task copyTask, CancellationToken cancellationToken)
   at Minio.MinioClient.<>c__DisplayClass13_0.<<GetObjectAsync>b__0>d.MoveNext() in /home/kp/code/minio-dotnet/Minio/ApiEndpoints/ObjectOperations.cs:line 173
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
```

**Comment by kannappanr** [comment]
@cklogs Closing this issue based on the above comment. Please feel free to reach out to us if you have further questions. You can also reach out to us at https://slack.min.io.

**Comment by damikun** [comment]
Hi im geting now this error any way how to deal wit it ?

![image](https://user-images.githubusercontent.com/54806834/85265842-2bf5f700-b473-11ea-9779-d5cf58db4b35.png)

**Comment by toxsedyshev** [comment]
Why this ticket is closed? 3+ years have passed and there is still no solution, only that workaround, which is not great. Callbacks in 2023? Are you serious?

BTW, no need in `options.AllowSynchronousIO = true;` already, there is async callback support:
```
var args = new GetObjectArgs()
    .WithObject(name)
    .WithBucket(bucketName)
    .WithCallbackStream((s, t) => s.CopyToAsync(outputStream, t));
var file = await _minio.GetObjectAsync(args, token);
```

But this is absolutely **not** cool.

One more related issue: https://github.com/minio/minio-dotnet/issues/225

**Comment by cdavernas** [comment]
@toxsedyshev I believe the solution is to stat the object prior in order to get its size, as said by @poornas.

> it causes ArgumentOutOfRangeException unless the CopyToAsync(stream, streamsize) variant is specified both in the API call and the invocation on the client side

I guess they do not want to force the client to call `Stat` underlyingly whenever calling `GetObjectAsync`, and doing so is instead up to the implementer.

Is that correct, @kannappanr?

**Comment by toxsedyshev** [comment]
@cdavernas I was sure I shared my async wrapper that is the solution to get rid of callbacks here. My bad. Here it is: https://stackoverflow.com/a/77158662/3334359

**Comment by cdavernas** [comment]
@toxsedyshev I had found  - and upvoted - your solution. 

In my use case, however, it does not do the trick: the implementation is hidden behind an interface method that must return a Stream. 

I guess I could adapt your solution by implementing a Stream, but doing the Stat call to het the object soze beforehand seems to cut it for me.
