### ISSUE TITLE
Impossible to create nested buckets via dotnet client

### ISSUE THREAD

**Issue by Sergey-Terekhin** [minio/minio-dotnet#347]
Hello!
We try to create nested buckets like directory tree: 
```
parent
   child1
        child2 etc.
``` 
In minio web interface it is possible to do by setting bucket name via slash (`/`) like `parent/child1/child2`
But then we try to do the same via dotnet client we receive validation exception:
```
Bucket name contains invalid characters.: Minio.Exceptions.InvalidBucketNameException: MinIO API responded with message=Bucket name contains invalid characters.
   at Minio.utils.ValidateBucketName(String bucketName) in /q/.q/sources/minio-dotnet/Minio/Helper/utils.cs:line 71
   at Minio.MinioClient.CreateRequest(Method method, String bucketName, String objectName, Dictionary`2 headerMap, String contentType, Object body, String resourcePath) in /q/.q/sources/minio-dotnet/Minio/MinioClient.cs:line 159
   at Minio.MinioClient.BucketExistsAsync(String bucketName, CancellationToken cancellationToken) in /q/.q/sources/minio-dotnet/Minio/ApiEndpoints/BucketOperations.cs:line 105
   at WebApi.Common.Storage.Classes.FileStorage.EnsureBucketExistsAsync(String bucketName, String location, CancellationToken token) in C:\Users\terekhin\sources\vizir-common-webapi\Storage\Classes\FileStorage.cs:line 100
```

**Comment by nitisht** [comment]
@Sergey-Terekhin you need to create the bucket `parent` and then create prefixes like `child1/child2/` while uploading objects

**Comment by nitisht** [comment]
yes like this 

```
    await minio.PutObjectAsync("parent",
                               "child1/child2/island.jpg",
                                filestream,
                                filestream.Length,
                               "application/octet-stream", ssec);
```

**Comment by kannappanr** [comment]
@Sergey-Terekhin closing this issue as answered. Please feel free to reach out to us at https://slack.min.io for such questions
