### ISSUE TITLE
Errors when uploading many files at once

### ISSUE THREAD

**Issue by lucius-the** [minio/minio-dotnet#364]
I'm testing minio with .net.
Minio is installed on a CentOS 8 VM with (2 CPU, 4 GB RAM) and given a 4 TB mount to use for storage.

I'm using minio-dotnet client to upload a little under 20,000 files.
I'm using 10 tasks, runing in parallel, each uploading it's slice of the entire set of files.
In each task I'm doing `Await mc.PutObjectAsync()` in a loop over a set of files.

After a while, I regularly get this error:
`MinIO API responded with message=Unsuccessful response from server without XML error: Only one usage of each socket address (protocol/network address/port) is normally permitted`

Stack trace:
```
   at Minio.MinioClient.ParseError(IRestResponse response) in /q/.q/sources/minio-dotnet/Minio/MinioClient.cs:line 468
   at Minio.MinioClient.HandleIfErrorResponse(IRestResponse response, IEnumerable`1 handlers, DateTime startTime) in /q/.q/sources/minio-dotnet/Minio/MinioClient.cs:line 526
   at Minio.MinioClient.ExecuteTaskAsync(IEnumerable`1 errorHandlers, IRestRequest request, CancellationToken cancellationToken) in /q/.q/sources/minio-dotnet/Minio/MinioClient.cs:line 370
   at Minio.MinioClient.PutObjectAsync(String bucketName, String objectName, String uploadId, Int32 partNumber, Byte[] data, Dictionary`2 metaData, Dictionary`2 sseHeaders, CancellationToken cancellationToken) in /q/.q/sources/minio-dotnet/Minio/ApiEndpoints/ObjectOperations.cs:line 497
   at Minio.MinioClient.PutObjectAsync(String bucketName, String objectName, Stream data, Int64 size, String contentType, Dictionary`2 metaData, ServerSideEncryption sse, CancellationToken cancellationToken) in /q/.q/sources/minio-dotnet/Minio/ApiEndpoints/ObjectOperations.cs:line 262
   at Minio.MinioClient.PutObjectAsync(String bucketName, String objectName, String fileName, String contentType, Dictionary`2 metaData, ServerSideEncryption sse, CancellationToken cancellationToken) in /q/.q/sources/minio-dotnet/Minio/ApiEndpoints/ObjectOperations.cs:line 202
   at MinioTest.Program.Upload(List`1 dFiles) in F:\SOURCES\MinioTest\MinioTest\Program.vb:line 36
```

I only have 10 connections to minio server, all are ESTABLISHED, no TIME_WAIT stuff, no large number of connections. It works for a while, then it starts showing this message.

I can't finish my uploads.

**Comment by lucius-the** [comment]
I'm using:
- minio server version 2019-12-30T05:45:39Z
- Minio 3.1.8 client from NuGet

**Comment by lucius-the** [comment]
Ok I think I found something..
netstat doesn't show a problem at the server side - but it DOES show a huge problem at the client side. Lots of connections in TIME_WAIT. Why ?

Any chance you are using httpclient (improperly, by not reusing it) ?

**Comment by harshavardhana** [comment]
Please upgrade to the latest release.
