### ISSUE TITLE
Backblaze B2 MultipartUpload failure

### ISSUE THREAD

**Issue by Alexr03** [minio/minio-dotnet#443]
Hello!
I seem to be facing the issue where Backblaze B2 will fail when uploading a file using the PutObjectAsync() with a file over 5mb.

**Trace:**
```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<InitiateMultipartUploadResult>
    <Bucket>admin-backups</Bucket>
    <Key>Unturned_D111ata.zip</Key>
    <UploadId>4_z4c274a8f0b62142b7d370919_f2010c49347dcee55_d20200703_m012955_c003_v0312002_t0017</UploadId>
</InitiateMultipartUploadResult>
```

**Exception:**
```
There is an error in XML document (2, 2).
   at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, XmlDeserializationEvents events)
   at System.Xml.Serialization.XmlSerializer.Deserialize(Stream stream)
   at Minio.MinioClient.<NewMultipartUploadAsync>d__22.MoveNext()
```

Help is appreciated :)
Thanks

**Comment by harshavardhana** [comment]
@Alexr03 please provide more detailed error and sample code..

**Comment by kannappanr** [comment]
the output from backblaze should be 
```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<InitiateMultipartUploadResult xmlns="http://s3.amazonaws.com/doc/2006-03-01/">
    <Bucket>admin-backups</Bucket>
    <Key>Unturned_D111ata.zip</Key>
    <UploadId>4_z4c274a8f0b62142b7d370919_f2010c49347dcee55_d20200703_m012955_c003_v0312002_t0017</UploadId>
</InitiateMultipartUploadResult>
```

**Comment by Alexr03** [comment]
@harshavardhana The "Complete File Uploader Example" is enough to reproduce this issue providing that the endpoint etc is Backblaze.

**Comment by kannappanr** [comment]
@Alexr03 

If you look at this sample piece of code
```
using System;
using System.IO;
using System.Xml.Serialization;

 [Serializable]
    [XmlRoot(ElementName = "InitiateMultipartUploadResult", Namespace = "http://s3.amazonaws.com/doc/2006-03-01/")]
    public class InitiateMultipartUploadResult
    {
        public string UploadId { get; set; }
    }
					
public class Program
{
	public static void Main()
	{
		string xml = "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?><InitiateMultipartUploadResult xmlns=\"http://s3.amazonaws.com/doc/2006-03-01/\"><Bucket>admin-backups</Bucket><Key>Unturned_D111ata.zip</Key><UploadId>4_z4c274a8f0b62142b7d370919_f2010c49347dcee55_d20200703_m012955_c003_v0312002_t0017</UploadId></InitiateMultipartUploadResult>";
		var contentBytes = System.Text.Encoding.UTF8.GetBytes(xml);
            InitiateMultipartUploadResult newUpload = null;
            using (var stream = new MemoryStream(contentBytes))
            {
                newUpload = (InitiateMultipartUploadResult)new XmlSerializer(typeof(InitiateMultipartUploadResult)).Deserialize(stream);
            }
            Console.WriteLine(newUpload.UploadId);
	}
}
```
this will work as the XML contains the namespace attribute `xmlns="http://s3.amazonaws.com/doc/2006-03-01/"`

**Comment by Alexr03** [comment]
@kannappanr Shall I reach out to Backblaze about this issue? as the response that comes back from Backblaze does not contain the XML namespace.

**Comment by harshavardhana** [comment]
> @kannappanr Shall I reach out to Backblaze about this issue? as the response that comes back from Backblaze does not contain the XML namespace.

yes xmlns is a way to provide a guarantee of contract for client unserialize to pick the right XML, it is not possible otherwise if server changes XML fields to look for correct value on the wire.

**Comment by Alexr03** [comment]
Update: Backblaze have passed it onto their engineer team.

**Comment by kannappanr** [comment]
@Alexr03 Closing this issue here. Please feel free to reach out to us if you still see issues once the fix has been made by backblaze
