### ISSUE TITLE
Multipart Uploads always fail - The specified key does not exist

### ISSUE THREAD

**Issue by Alumniminium** [minio/minio-dotnet#499]
Small files work, >5mb fails. I run the binary, not docker and it's behind a nginx reverse proxy. I can upload big files using the web-ui, nginx client body size is uncapped. 
the dotnet minio library however always fails if the file is bigger than 5 megs.

minio 3.1.13, net5, linux-x64

```
await client.PutObjectAsync(Configuration.BucketName, $"{Configuration.Folder}/{fileName}",new MemoryStream(workItem.TargetFile),workItem.TargetFile.LongLength);
```
_workItem.TargetFile.LongLength: 5373295 (~5.3mb)
{Configuration.Folder}/{fileName}: is always audio/[GUID].mp3
eg.: audio/1cf9ea10-ebf1-465c-9910-9bf94cb07080.mp3_

```
MinIO API responded with message=The specified key does not exist.
   at Minio.MinioClient.ParseErrorFromContent(IRestResponse response) in /q/.q/sources/minio-dotnet/Minio/MinioClient.cs:line 570
   at Minio.MinioClient.ParseError(IRestResponse response) in /q/.q/sources/minio-dotnet/Minio/MinioClient.cs:line 430
   at Minio.MinioClient.<>c.<.ctor>b__84_0(IRestResponse response) in /q/.q/sources/minio-dotnet/Minio/MinioClient.cs:line 81
   at Minio.MinioClient.HandleIfErrorResponse(IRestResponse response, IEnumerable`1 handlers, DateTime startTime) in /q/.q/sources/minio-dotnet/Minio/MinioClient.cs:line 604
   at Minio.MinioClient.ExecuteTaskCoreAsync(IEnumerable`1 errorHandlers, IRestRequest request, CancellationToken cancellationToken) in /q/.q/sources/minio-dotnet/Minio/MinioClient.cs:line 404
   at Minio.MinioClient.NewMultipartUploadAsync(String bucketName, String objectName, Dictionary`2 metaData, Dictionary`2 sseHeaders, CancellationToken cancellationToken) in /q/.q/sources/minio-dotnet/Minio/ApiEndpoints/ObjectOperations.cs:line 484
   at Minio.MinioClient.PutObjectAsync(String bucketName, String objectName, Stream data, Int64 size, String contentType, Dictionary`2 metaData, ServerSideEncryption sse, CancellationToken cancellationToken) in /q/.q/sources/minio-dotnet/Minio/ApiEndpoints/ObjectOperations.cs:line 312
   at Minio.MinioClient.PutObjectAsync(String bucketName, String objectName, String fileName, String contentType, Dictionary`2 metaData, ServerSideEncryption sse, CancellationToken cancellationToken) in /q/.q/sources/minio-dotnet/Minio/ApiEndpoints/ObjectOperations.cs:line 241
```

The same code works fine when pointed at an amazon s3 endpoint though...

**Comment by kannappanr** [comment]
@Alumniminium Can you please paste the entire code and your nginx config settings for us to reproduce the issue. Also, are you seeing this issue if the client is talking directly to minio, by skipping nginx?

**Comment by kannappanr** [comment]
Closing this issue. Will reopen when there is a response from the reporter

**Comment by vuonghung12** [comment]
@Alumniminium hi I have same problem
did you resolve your problem
