### ISSUE TITLE
minio-dotnet cannot create buckets in different region

### ISSUE THREAD

**Issue by chnyda** [minio/minio-dotnet#558]
Nuget Version: 3.1.13 

It is not possible to create buckets when minio's region does not have the default value.
Strangely, it is possible to use regions `PutObjectAsync` with different region configured in MinioClient.
ListBuckets does not care about region.

```
            var client = new MinioClient("xxxx", "xxxx", "xxxxxxxx" ).WithSSL();
            await client.MakeBucketAsync("my-new-bucket", "taikun-east-1");
```

returns:
```
Unhandled exception. Minio.Exceptions.UnexpectedMinioException: MinIO API responded with message=The authorization header is malformed; the region is wrong; expecting 'taikun-east-1'.
   at Minio.MinioClient.ParseErrorFromContent(IRestResponse response) in /q/.q/sources/minio-dotnet/Minio/MinioClient.cs:line 570
   at Minio.MinioClient.ParseError(IRestResponse response) in /q/.q/sources/minio-dotnet/Minio/MinioClient.cs:line 430
   at Minio.MinioClient.<>c.<.ctor>b__84_0(IRestResponse response) in /q/.q/sources/minio-dotnet/Minio/MinioClient.cs:line 81
   at Minio.MinioClient.HandleIfErrorResponse(IRestResponse response, IEnumerable`1 handlers, DateTime startTime) in /q/.q/sources/minio-dotnet/Minio/MinioClient.cs:line 604
   at Minio.MinioClient.ExecuteTaskCoreAsync(IEnumerable`1 errorHandlers, IRestRequest request, CancellationToken cancellationToken) in /q/.q/sources/minio-dotnet/Minio/MinioClient.cs:line 404
   at Minio.MinioClient.MakeBucketAsync(String bucketName, String location, CancellationToken cancellationToken) in /q/.q/sources/minio-dotnet/Minio/ApiEndpoints/BucketOperations.cs:line 98
   at ConsoleApp16.Program.Main(String[] args) in /Users/cedrichnyda/RiderProjects/ConsoleApp16/ConsoleApp16/Program.cs:line 23
   at ConsoleApp16.Program.<Main>(String[] args)

```

When I try to specify the region name in the constructor: 
```
            var client = new MinioClient("xxxx", "xxxx", "xxxxxxxx", "taikun-east-1").WithSSL();
            await client.MakeBucketAsync("my-new-bucket", "taikun-east-1");
```
it returns 
```
Unhandled exception. Minio.Exceptions.UnexpectedMinioException: MinIO API responded with message=The XML you provided was not well-formed or did not validate against our published schema.
   at Minio.MinioClient.ParseErrorFromContent(IRestResponse response) in /q/.q/sources/minio-dotnet/Minio/MinioClient.cs:line 570
   at Minio.MinioClient.ParseError(IRestResponse response) in /q/.q/sources/minio-dotnet/Minio/MinioClient.cs:line 430
   at Minio.MinioClient.<>c.<.ctor>b__84_0(IRestResponse response) in /q/.q/sources/minio-dotnet/Minio/MinioClient.cs:line 81
   at Minio.MinioClient.HandleIfErrorResponse(IRestResponse response, IEnumerable`1 handlers, DateTime startTime) in /q/.q/sources/minio-dotnet/Minio/MinioClient.cs:line 604
   at Minio.MinioClient.ExecuteTaskCoreAsync(IEnumerable`1 errorHandlers, IRestRequest request, CancellationToken cancellationToken) in /q/.q/sources/minio-dotnet/Minio/MinioClient.cs:line 404
   at Minio.MinioClient.MakeBucketAsync(String bucketName, String location, CancellationToken cancellationToken) in /q/.q/sources/minio-dotnet/Minio/ApiEndpoints/BucketOperations.cs:line 98
   at ConsoleApp16.Program.Main(String[] args) in /Users/cedrichnyda/RiderProjects/ConsoleApp16/ConsoleApp16/Program.cs:line 23
   at ConsoleApp16.Program.<Main>(String[] args)

```

**Comment by realZhangChi** [comment]
This happened to me too. Any news?

**Comment by harshavardhana** [comment]
Please upgrade to the latest release.
