### ISSUE TITLE
ListenBucketNotificationsAsync fails for 2 different events

### ISSUE THREAD

**Issue by sowri1** [minio/minio-dotnet#571]
I have been using minio sdk for python for listening bucket notifications and it works brilliantly.  When coming to using C# sdk, it works when using only one eventtype like ```EventType.ObjectCreatedAll``` or ```EventType.ObjectRemovedAll``` but not both. I get the error when runnning the code
```
IList<EventType> events = new List<EventType> { EventType.ObjectCreatedAll, EventType.ObjectRemovedAll };
IObservable<MinioNotificationRaw> observable = this.minio.ListenBucketNotificationsAsync(this.bucket_name, events, this.remote_path);

IDisposable subscription = observable.Subscribe(
                    notification => Console.WriteLine(notification.json.ToString()),
                    ex => Console.WriteLine($"OnError: {ex}"),
                    () => Console.WriteLine($"Stopped listening for bucket notifications\n"));
``` 

This is the error I get.
```
OnError: System.ArgumentException: An item with the same key has already been added. Key: events
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at Minio.V4Authenticator.GetCanonicalRequest(IRestRequest request, SortedDictionary`2 headersToSign) in /q/.q/sources/minio-dotnet/Minio/V4Authenticator.cs:line 402
   at Minio.V4Authenticator.Authenticate(IRestClient client, IRestRequest request) in /q/.q/sources/minio-dotnet/Minio/V4Authenticator.cs:line 122
   at RestSharp.RestClient.AuthenticateIfNeeded(IRestRequest request)
   at RestSharp.RestClient.ExecuteAsync(IRestRequest request, Action`2 callback, String httpMethod, Func`4 getWebRequest)
   at RestSharp.RestClient.ExecuteAsync(IRestRequest request, Action`2 callback, Method httpMethod)
   at RestSharp.RestClient.ExecuteAsync(IRestRequest request, Action`2 callback)
   at RestSharp.RestClient.ExecuteAsync(IRestRequest request, CancellationToken token)
--- End of stack trace from previous location ---
   at Minio.MinioClient.ExecuteTaskCoreAsync(IEnumerable`1 errorHandlers, IRestRequest request, CancellationToken cancellationToken) in /q/.q/sources/minio-dotnet/Minio/MinioClient.cs:line 402
   at Minio.MinioClient.<>c__DisplayClass11_0.<<ListenBucketNotificationsAsync>b__0>d.MoveNext() in /q/.q/sources/minio-dotnet/Minio/ApiEndpoints/BucketOperations.cs:line 435
```

**Comment by harshavardhana** [comment]
Please upgrade to the latest release
