### ISSUE TITLE
Access denied on ListObjectsAsync()

### ISSUE THREAD

**Issue by eymentopcuoglu** [minio/minio-dotnet#606]
Hi, 

I was trying to setup a structure where certain users are not allowed to access a specific path. Here is the case:

We have a bucket named `dev`  which contains `home/`, `technician/` and `admin/` directories. Inside these directories we have a file per each, for the sake of simplicity. We want the users with the policy `dev-admin` to access `home/` and `admin/` directories. And for the users with the policy `dev-technician`, we want them to access `home/` and `technician/` directories.

To achieve this, I created a user group `dev `, which has the members `dev-admin` and `dev-technician`. Here is the IAM policy for `dev`:

```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "AllowGroupToSeeBucketListInTheConsole",
            "Effect": "Allow",
            "Action": [
                "s3:GetBucketLocation",
                "s3:ListAllMyBuckets"
            ],
            "Resource": [
                "arn:aws:s3:::*"
            ]
        },
        {
            "Sid": "AllowRootAndHomeListingInBucket",
            "Effect": "Allow",
            "Action": [
                "s3:ListBucket"
            ],
            "Resource": [
                "arn:aws:s3:::dev"
            ],
            "Condition": {
                "StringEquals": {
                    "s3:prefix": [
                        "",
                        "home/"
                    ]
                }
            }
        }
    ]
}
```

The IAM policy for `dev-admin`:
```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "s3:ListBucket"
            ],
            "Resource": [
                "arn:aws:s3:::dev"
            ],
            "Condition": {
                "StringLike": {
                    "s3:prefix": [
                        "admin/"
                    ]
                }
            }
        }
    ]
}
```

The IAM policy for `dev-technician`:
```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "s3:ListBucket"
            ],
            "Resource": [
                "arn:aws:s3:::dev"
            ],
            "Condition": {
                "StringLike": {
                    "s3:prefix": [
                        "technician/"
                    ]
                }
            }
        }
    ]
}
```

Note that these configurations are just for listing, I haven't configured for the other operations yet.

So the problem is, when I try to access the directoy `home/`  with the user `dev-technician`, I get `(MinIO API responded with message=Access denied on the resource: /dev/)` with dotnet SDK. Here is the code:
```csharp
using Minio;
using Minio.DataModel;

var minio = new MinioClient()
    .WithEndpoint("192.168.1.20",9000)
    .WithCredentials("dev-technician", "dev123")
    .Build();
    
try
{
    ListObjectsArgs listArgs = new ListObjectsArgs()
        .WithBucket("dev")
        .WithPrefix("home/");
    
    IObservable<Item> observable = minio.ListObjectsAsync(listArgs);
    
    IDisposable subscription = observable.Subscribe(
        item => Console.WriteLine("OnNext: {0}", item.Key),
        ex => Console.WriteLine($"OnError: {ex}"),
        () => Console.WriteLine($"Listed all objects in bucket dev\n"));
}
catch (Exception e)
{
    Console.WriteLine($"[Bucket]  Exception: {e}");
}
```

Output:
```
[Bucket]  Exception: System.AggregateException: One or more errors occurred. (MinIO API responded with message=Access denied on the resource: /dev/)
 ---> Minio.Exceptions.AccessDeniedException: MinIO API responded with message=Access denied on the resource: /dev/
   at Minio.MinioClient.ParseWellKnownErrorNoContent(ResponseResult response) in /q/.q/sources/minio-dotnet/Minio/MinioClient.cs:line 716
   at Minio.MinioClient.ParseErrorNoContent(ResponseResult response) in /q/.q/sources/minio-dotnet/Minio/MinioClient.cs:line 622
   at Minio.MinioClient.ParseError(ResponseResult response) in /q/.q/sources/minio-dotnet/Minio/MinioClient.cs:line 607
   at Minio.MinioClient.<>c.<.ctor>b__168_0(ResponseResult response) in /q/.q/sources/minio-dotnet/Minio/MinioClient.cs:line 89
   at Minio.MinioClient.HandleIfErrorResponse(ResponseResult response, IEnumerable`1 handlers, DateTime startTime) in /q/.q/sources/minio-dotnet/Minio/MinioClient.cs:line 834
   at Minio.MinioClient.ExecuteTaskCoreAsync(IEnumerable`1 errorHandlers, HttpRequestMessageBuilder requestMessageBuilder, CancellationToken cancellationToken) in /q/.q/sources/minio-dotnet/Minio/MinioClient.cs:line 585
   at Minio.MinioClient.BucketExistsAsync(BucketExistsArgs args, CancellationToken cancellationToken) in /q/.q/sources/minio-dotnet/Minio/ApiEndpoints/BucketOperations.cs:line 77
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.WaitAllCore(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.WaitAll(Task[] tasks)
   at Minio.MinioClient.ListObjectsAsync(ListObjectsArgs args, CancellationToken cancellationToken) in /q/.q/sources/minio-dotnet/Minio/ApiEndpoints/BucketOperations.cs:line 259
   at Program.<Main>$(String[] args) in C:\Users\xParadokSx\RiderProjects\minio-test\minio-test\Program.cs:line 15

Process finished with exit code 0.
```

I tried the same with Java SDK and it worked. Here is the code:
```java
import io.minio.ListObjectsArgs;
import io.minio.MinioClient;
import io.minio.Result;
import io.minio.errors.*;
import io.minio.messages.Item;

import java.io.IOException;
import java.security.InvalidKeyException;
import java.security.NoSuchAlgorithmException;

public class Main {
    public static void main(String[] args) throws IOException, InvalidKeyException, InvalidResponseException, InsufficientDataException, NoSuchAlgorithmException, ServerException, InternalException, XmlParserException, ErrorResponseException {

        MinioClient minioClient =
                MinioClient.builder()
                        .endpoint("192.168.1.20",9000,false)
                        .credentials("dev-technician", "dev123")
                        .build();

        Iterable<Result<Item>> results = minioClient.listObjects(
                ListObjectsArgs.builder()
                        .bucket("dev")
                        .prefix("home/")
                        .build());

        for (Result<Item> result : results) {
            Item item = result.get();
            System.out.println(item.objectName());
        }
    }
}
```

Output:
```
home/example.pdf
Process finished with exit code 0
```
What do you think might be the issue?

Thank you!

**Comment by harshavardhana** [comment]
this is because `s3;prefix` is not set when its empty.

**Comment by eymentopcuoglu** [comment]
Are you referring here:
```json
"Condition": {
                "StringEquals": {
                    "s3:prefix": [
                        "",
                        "home/"
                    ]
                }
            }
```
If so, why do you think in Java SDK it works? What should I do to make it work in dotnet SDK?
