### ISSUE TITLE
Version 4.0.6 gets "MinIO API responded with message=Connection error:Object reference not set to an instance of an object"

### ISSUE THREAD

**Issue by CasperCBroeren** [minio/minio-dotnet#714]
When doing a upgrade from 4.0.5 to 4.06 we experienced odd behavior when using Minio client

BucketExistsAsync (and any other call)
```
Minio.Exceptions.ConnectionException: MinIO API responded with message=Connection error:Object reference not set to an instance of an object.. Status code=0, response=Object reference not set to an instance of an object., content=
   at Minio.MinioClient.ParseErrorNoContent(ResponseResult response) in /root/.q/sources/minio-dotnet/Minio/MinioClient.cs:line 613
   at Minio.MinioClient.ParseError(ResponseResult response) in /root/.q/sources/minio-dotnet/Minio/MinioClient.cs:line 596
   at Minio.MinioClient.HandleIfErrorResponse(ResponseResult response, IEnumerable`1 handlers, DateTime startTime) in /root/.q/sources/minio-dotnet/Minio/MinioClient.cs:line 793
   at Minio.MinioClient.ExecuteTaskCoreAsync(IEnumerable`1 errorHandlers, HttpRequestMessageBuilder requestMessageBuilder, CancellationToken cancellationToken, Boolean isSts) in /root/.q/sources/minio-dotnet/Minio/MinioClient.cs:line 574
   at Minio.BucketRegionCache.Update(MinioClient client, String bucketName) in /root/.q/sources/minio-dotnet/Minio/BucketRegionCache.cs:line 102
   at Minio.MinioClient.GetRegion(String bucketName) in /root/.q/sources/minio-dotnet/Minio/MinioClient.cs:line 216
   at Minio.MinioClient.CreateRequest(HttpMethod method, String bucketName, String objectName, Dictionary`2 headerMap, String contentType, Byte[] body, String resourcePath) in /root/.q/sources/minio-dotnet/Minio/MinioClient.cs:line 301
   at Minio.MinioClient.CreateRequest[T](BucketArgs`1 args) in /root/.q/sources/minio-dotnet/Minio/MinioClient.cs:line 246
   at Minio.MinioClient.BucketExistsAsync(BucketExistsArgs args, CancellationToken cancellationToken) in /root/.q/sources/minio-dotnet/Minio/ApiEndpoints/BucketOperations.cs:line 74
```
Connection code
![image](https://user-images.githubusercontent.com/18749643/201309020-ec0641d0-3de0-4aac-befb-a1101b943a4e.png)
Interaction code
![image](https://user-images.githubusercontent.com/18749643/201308940-c1870420-407f-4b06-9718-f6c5f6e44834.png)

Server minio; 
![image](https://user-images.githubusercontent.com/18749643/201308398-add5bad2-ac7c-499b-9add-81423c1eeacd.png)

**Comment by Kampfmoehre** [comment]
We have the same problem with PutObjectAsync, setup is similar. We are using version `2022-01-08T03:11:54Z`. Is there anything we can to apart from downgrading Minio Dotnet?

**Comment by okandeldev** [comment]
@CasperCBroeren, please make sure to call Build for minioClient Instance.

![image](https://user-images.githubusercontent.com/64110109/201785233-5795689a-188a-451f-a1e3-546aa0bc9cb9.png)

**Comment by ebozduman** [comment]
Thank you @okandeldev 

@CasperCBroeren,
`Build()` method is required to be called when a new MinioClient instance is created.
Please add the missing call, try again if possible and report the behavior change.
Feel free to close the issue if you don't see any problems.

@Kampfmoehre,
I am not sure if you have a different case as we don't know the internals and details of your scenario.
I'd recommend to file a separate issue with all the details of your setup, even if the symptoms/error messages you get look similar or the same.

**Comment by Kampfmoehre** [comment]
> @Kampfmoehre,
> I am not sure if you have a different case as we don't know the internals and details of your scenario.
> I'd recommend to file a separate issue with all the details of your setup, even if the symptoms/error messages you get look similar or the same.

Thx for the hint, I just checked and for us the call to build() is also missing.

**Comment by okandeldev** [comment]
> We have the same problem with PutObjectAsync, setup is similar. We are using version `2022-01-08T03:11:54Z`. Is there anything we can to apart from downgrading Minio Dotnet?

@Kampfmoehre 
Kindly , you need to check the stream position is set to zero before calling **PutObjectAsync** method.

![image](https://user-images.githubusercontent.com/64110109/201911430-af818846-cd9a-40f8-a859-f1217b62ed0a.png)

![image](https://user-images.githubusercontent.com/64110109/201911184-53ef1d3a-19bf-435d-87a0-2a6184e9a825.png)
