### ISSUE TITLE
BucketExistsAsync fail when using direct minio server ip

### ISSUE THREAD

**Issue by vuonghung12** [minio/minio-dotnet#716]
Hi, when I setup minio behind nginx proxy
method BucketExistsAsync work

but when change to direct ip I have this error, please help

InnerException: {"<html xmlns=''> was not expected."
Message: There is an error in XML document (1, 2).
StackTrace:
```
   at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, XmlDeserializationEvents events)
   at System.Xml.Serialization.XmlSerializer.Deserialize(Stream stream)
   at Minio.MinioClient.ParseErrorFromContent(ResponseResult response)
   at Minio.MinioClient.ParseError(ResponseResult response)
   at Minio.MinioClient.HandleIfErrorResponse(ResponseResult response, IEnumerable`1 handlers, DateTime startTime)
   at Minio.MinioClient.<ExecuteTaskCoreAsync>d__181.MoveNext()
   at Minio.BucketRegionCache.<Update>d__9.MoveNext()
   at Minio.MinioClient.<GetRegion>d__168.MoveNext()
   at Minio.MinioClient.<CreateRequest>d__172.MoveNext()
   at Minio.MinioClient.<CreateRequest>d__170`1.MoveNext()
   at Minio.MinioClient.<BucketExistsAsync>d__1.MoveNext()
```

**Comment by ebozduman** [comment]
Could you provide your complete script and console messages? 
Please include your env vars if you depend on them and the output of `mc admin trace --debug -v <your-alias>` command during your run.

**Comment by vuonghung12** [comment]
code: bool found = await minio.BucketExistsAsync(bucketName);
logs: 
![image](https://user-images.githubusercontent.com/109650476/203457247-a54ab582-ba34-4e7b-bd20-2a13c41c7a99.png)
Trace:
![image](https://user-images.githubusercontent.com/109650476/203457461-99d4052b-06f8-4f58-8c1e-b1135885ede8.png)

I can't find debug option on web-ui
