### ISSUE TITLE
.NET client problem at stream upload for larger files than 5MB

### ISSUE THREAD

**Issue by mihais-cvu** [minio/minio-dotnet#735]
Hello.
I cannot upload files larger than 5MB using only the stream upload when I'm setting arguments like this:
```
var args = new PutObjectArgs()
	.WithBucket(bucketName)
    .WithObject(objectName)
    .WithStreamData(fileStream)
    .WithObjectSize(fileStream.Length)
    .WithContentType("application/octet-stream")
    .WithContentType("application/pdf")
    .WithContentType("application/json");

```
I get the following exception:

```
[Bucket]  Exception: System.ObjectDisposedException: Cannot access a closed file.
   at System.IO.FileStream.get_Position()
   at Microsoft.AspNetCore.Http.ReferenceReadStream.VerifyPosition()
   at Microsoft.AspNetCore.Http.ReferenceReadStream.ReadAsync(Memory`1 buffer, CancellationToken cancellationToken)
   at Minio.MinioClient.ReadFullAsync(Stream data, Int32 currentPartSize) in /root/.q/sources/minio-dotnet/Minio/ApiEndpoints/ObjectOperations.cs:line 1617
   at Minio.MinioClient.PutObjectPartAsync(PutObjectPartArgs args, CancellationToken cancellationToken) in /root/.q/sources/minio-dotnet/Minio/ApiEndpoints/ObjectOperations.cs:line 1198
   at Minio.MinioClient.PutObjectAsync(PutObjectArgs args, CancellationToken cancellationToken) in /root/.q/sources/minio-dotnet/Minio/ApiEndpoints/ObjectOperations.cs:line 633
   at MDocs.Api.Services.MinioService.ObjectUpload(String bucketName, String objectName, Stream fileStream) in D:\Mxxx\Mxxxx\src\Mxxxx.Api\Services\MinioService.cs:line 72
```

The file upload works fine when I'm using the path for the file without opening the stream. But for my use case I need to use only the stream upload.
Thanks in advance.

**Comment by mkc-xuliangjie** [comment]
第一步：
	PresignedPutObjectArgs args = new PresignedPutObjectArgs()
														.WithBucket(bucketName)
														.WithObject(objectName)
														.WithExpiry(expiresInt);

				return minio.PresignedPutObjectAsync(args).Result;

获取到
presigned URL:
http://10.0.70.220:9000/bucketName/20230330/b45dd2506dc24d758c0a980796f6682e.docx?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=minioadmin%2F20230330%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20230330T031120Z&X-Amz-Expires=302400&X-Amz-SignedHeaders=host&X-Amz-Signature=e44e9d1dbf81dd4eee559b716ca515e579c8c5fe19d114093bdc5f07e120f533


第二步：

var axios = require('axios');
var FormData = require('form-data');
var fs = require('fs');
var data = new FormData();
data.append('', fs.createReadStream('/C:/Users/xulj/Desktop/02_考勤机和考勤系统设置.docx'));

var config = {
  method: 'put',
  url: 'http://10.0.70.220:9000/bucketName/20230330/b45dd2506dc24d758c0a980796f6682e.docx?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=minioadmin%2F20230330%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20230330T031120Z&X-Amz-Expires=302400&X-Amz-SignedHeaders=host&X-Amz-Signature=e44e9d1dbf81dd4eee559b716ca515e579c8c5fe19d114093bdc5f07e120f533',
  headers: { 
    ...data.getHeaders()
  },
  data : data
};

axios(config)
.then(function (response) {
  console.log(JSON.stringify(response.data));
})
.catch(function (error) {
  console.log(error);
});

思路：获取到上传地址，直接走本地FTP上传。

**Comment by martijn00** [comment]
@mihais-cvu is this still the case with the 5.0.0 update?

**Comment by harshavardhana** [comment]
Thank you for your report! This repository recently went through a significant architectural overhaul (see #1363 — fully rewritten .NET Core based SDK). As a result, the codebase structure has changed substantially and this issue may no longer be applicable. We are closing it as part of this cleanup. If this problem still affects you with the updated codebase, please open a new issue with updated details.
