### ISSUE TITLE
WithCallbackStream ASYNC stream causes Exception

### ISSUE THREAD

**Issue by robertvo** [minio/minio-dotnet#758]
When I do release build and use .WithCallbackStream(async stream=>{})
I get the exception bellow. This is not happening in debug build. If I remove the async from the WithCallbackStream callback and make it synch, everything works fine. Very strange.

    public static async Task<MemoryStream> DownloadAsync(this MinioClient minio, string source_bucket, string objectKey, int expected_size = 8 * 1024)
    {

        var ms = new MemoryStream(expected_size);

        GetObjectArgs getObjectArgs = new GetObjectArgs()
            .WithBucket(source_bucket)
            .WithObject(objectKey)
            .WithCallbackStream(async stream =>
            {
                await stream.CopyToAsync(ms).ConfigureAwait(false) ;
                stream.Dispose();
            });

        await minio.GetObjectAsync(getObjectArgs);

        ms.Position = 0;

        return ms;
    }

System.IO.IOException: The read operation failed, see inner exception.
 ---> System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'System.Net.Sockets.NetworkStream'.
   at System.Net.Sockets.NetworkStream.ReadAsync(Memory`1 buffer, CancellationToken cancellationToken)
   at System.Net.Security.SslStream.EnsureFullTlsFrameAsync[TIOAdapter](CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource<TResult>.GetResult(Int16 token)
   at System.Net.Security.SslStream.ReadAsyncInternal[TIOAdapter](Memory`1 buffer, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Security.SslStream.ReadAsyncInternal[TIOAdapter](Memory`1 buffer, CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource<TResult>.GetResult(Int16 token)
   at System.Net.Http.HttpConnection.FillAsync(Boolean async)
   at System.Net.Http.HttpConnection.CopyToContentLengthAsync(Stream destination, Boolean async, UInt64 length, Int32 bufferSize, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnection.ContentLengthReadStream.CompleteCopyToAsync(Task copyTask, CancellationToken cancellationToken)
   at MinioExtensions.<>c__DisplayClass2_0.<<DownloadAsync>b__0>d.MoveNext() in Extensions.cs:line 139
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()

**Comment by tinohager** [comment]
I also had strange dispose problems
```cs

var getObjectArgs = new GetObjectArgs()
    .WithBucket(source_bucket)
    .WithObject(objectKey)
    .WithCallbackStream(async (callbackStream) =>
    {
        await callbackStream.CopyToAsync(memoryStream, cancellationToken);
        memoryStream.Position = 0;
    });
```

Now it looks better the cancellation token now comes from `WithCallbackStream` and also additionally there is the `DisposeAsync` call at the end

```cs
var getObjectArgs = new GetObjectArgs()
    .WithBucket(source_bucket)
    .WithObject(objectKey)
    .WithCallbackStream(async (callbackStream, cancellationToken) =>
    {
        await callbackStream.CopyToAsync(memoryStream, cancellationToken);
        memoryStream.Position = 0;
        await callbackStream.DisposeAsync();
    });
```
