### ISSUE TITLE
MinIO API responded with message=Not found.

### ISSUE THREAD

**Issue by JeremyWu917** [minio/minio-dotnet#863]
Hi,
I use `Minio 5.0.0` from NuGet in Net6.0 project and I got a issue when I download a object from bucket.
Please help to check and advise
Thanks

## MinIO Version
```
minio.exe --version
minio.exe version RELEASE.2023-08-04T17-40-21Z (commit-id=cb089dcb52f0bc8eb58a4c991dfd92a0fec13e62)
Runtime: go1.19.12 windows/amd64
License: GNU AGPLv3 <https://www.gnu.org/licenses/agpl-3.0.html>
Copyright: 2015-2023 MinIO, Inc.
```
## OS Version
```
Edition	Windows 11 Pro
Version	22H2
Installed on	‎2023-‎01-‎30
OS build	22621.2215
Experience	Windows Feature Experience Pack 1000.22662.1000.0
```

## Demo
```
// See https://aka.ms/new-console-template for more information
using Minio.DataModel;
using Minio;

Console.WriteLine("Hello, World!");

var client = new MinioClient()
        .WithEndpoint("localhost:9000")
        .WithCredentials("minioadmin", "minioadmin")
        .Build();

FGetObject.Run(client);

Console.ReadKey();

internal static class FGetObject
{
    // Download object from bucket into local file
    public static async Task Run(IMinioClient minio,
        string bucketName = "pv-el-test",
        string objectName = "d6407b95054a4e3780bc8b96537ed0f5.jpg",
        string fileName = @"C:\filecache\1.jpg",
        IServerSideEncryption sse = null)
    {
        try
        {
            Console.WriteLine("Running example for API: GetObjectAsync");
            File.Delete(fileName);
            var args = new GetObjectArgs()
                .WithBucket(bucketName)
                .WithObject(objectName)
                .WithFile(fileName)
                .WithServerSideEncryption(sse);
            _ = await minio.GetObjectAsync(args).ConfigureAwait(false);
            Console.WriteLine($"Downloaded the file {fileName} from bucket {bucketName}");
            Console.WriteLine();
        }
        catch (Exception e)
        {
            Console.WriteLine($"[Bucket]  Exception: {e}");
        }
    }
}
```
## Issues
![image](https://github.com/minio/minio-dotnet/assets/54832272/00633d0d-ba7c-4ec8-9ae7-d0a73652dff5)

**Comment by JeremyWu917** [comment]
If I update the build to below, the new issues cames
```
var client = new MinioClient()
        .WithEndpoint("localhost:9000")
        .WithCredentials("minioadmin", "minioadmin")
        .WithSSL()
        .Build();
```

```
Error occurred: Minio.Exceptions.ConnectionException: MinIO API responded with message=Connection error:The SSL connection could not be established, see inner exception.. Status code=0, response=The SSL connection could not be established, see inner exception., content=
   at Minio.MinioClient.ParseErrorNoContent(ResponseResult response) in /q/.q/sources/minio-dotnet/Minio/MinioClient.cs:line 623
   at Minio.MinioClient.ParseError(ResponseResult response) in /q/.q/sources/minio-dotnet/Minio/MinioClient.cs:line 604
   at Minio.MinioClient.HandleIfErrorResponse(ResponseResult response, IEnumerable`1 handlers, DateTime startTime) in /q/.q/sources/minio-dotnet/Minio/MinioClient.cs:line 831
   at Minio.MinioClient.ExecuteTaskCoreAsync(IEnumerable`1 errorHandlers, HttpRequestMessageBuilder requestMessageBuilder, CancellationToken cancellationToken) in /q/.q/sources/minio-dotnet/Minio/MinioClient.cs:line 582
   at Minio.BucketRegionCache.Update(MinioClient client, String bucketName) in /q/.q/sources/minio-dotnet/Minio/BucketRegionCache.cs:line 103
   at Minio.MinioClient.GetRegion(String bucketName) in /q/.q/sources/minio-dotnet/Minio/MinioClient.cs:line 142
   at Minio.MinioClient.CreateRequest(HttpMethod method, String bucketName, String objectName, Dictionary`2 headerMap, String contentType, Byte[] body, String resourcePath) in /q/.q/sources/minio-dotnet/Minio/MinioClient.cs:line 232
   at Minio.MinioClient.CreateRequest[T](ObjectArgs`1 args) in /q/.q/sources/minio-dotnet/Minio/MinioClient.cs:line 191
   at Minio.MinioClient.StatObjectAsync(StatObjectArgs args, CancellationToken cancellationToken) in /q/.q/sources/minio-dotnet/Minio/ApiEndpoints/ObjectOperations.cs:line 119
   at Program.<Main>$(String[] args) in C:\Users\WYT\Desktop\ConsoleApp1\ConsoleApp1\Program.cs:line 66

C:\Users\WYT\Desktop\ConsoleApp1\ConsoleApp1\bin\Debug\net6.0\ConsoleApp1.exe (process 14956) exited with code 0.
To automatically close the console when debugging stops, enable Tools->Options->Debugging->Automatically close the console when debugging stops.
Press any key to close this window . . .
```

So, if there is not https configed , what can I do to fix this issue?

**Comment by JeremyWu917** [comment]
It's done from upgrade SDK version 5.0.0 to 4.0.2 🙃
