### ISSUE TITLE
Fix flaky functional test on ListenBucketNotification()

### ISSUE THREAD

**Issue by harshavardhana** [minio/minio-dotnet#870]
```
Run wget --quiet -O /tmp/minio https://dl.min.io/server/minio/release/linux-amd64/minio
WARNING: MINIO_ACCESS_KEY and MINIO_SECRET_KEY are deprecated.
         Please use MINIO_ROOT_USER and MINIO_ROOT_PASSWORD
Formatting 1st pool, 1 set(s), 4 drives per set.
WARNING: Host local has more than 2 drives of set. A host failure will result in data becoming unavailable.
MinIO Object Storage Server
Copyright: 2015-2023 MinIO, Inc.
License: GNU AGPLv3 <https://www.gnu.org/licenses/agpl-3.0.html>
Version: RELEASE.2023-09-04T19-57-37Z (go1.19.12 linux/amd64)

Status:         4 Online, 0 Offline. 
S3-API: https://10.1.0.[25](https://github.com/minio/minio-dotnet/actions/runs/6099001365/job/16550314502#step:4:26)0:9000  https://172.17.0.1:9000  https://127.0.0.1:9000     
Console: https://10.1.0.250:44479 https://172.17.0.1:44479 https://127.0.0.1:44479   

Documentation: https://min.io/docs/minio/linux/index.html
{"Name":"minio-dotnet : ListenBucketNotificationsAsync_Test1","Function":"IObservable<MinioNotificationRaw> ListenBucketNotificationsAsync(ListenBucketNotificationsArgs args, CancellationToken cancellationToken = default(CancellationToken))","Description":"Tests whether ListenBucketNotifications passes for small object","Args":{"bucketName":"minio-dotnet-example-qwes01ymg1am5wl","objectName":"minio-dotnet-example-myzhbssq9h","contentType":"application/octet-stream","size":"1KB"},"Duration":1040,"Status":"FAIL","Alert":"MinIO API responded with message=Failed to detect the expected bucket notification event.","Message":"Minio.Exceptions.UnexpectedMinioException: MinIO API responded with message=Failed to detect the expected bucket notification event.\n   at Minio.Functional.Tests.FunctionalTest.ListenBucketNotificationsAsync_Test1(IMinioClient minio) in /_/Minio.Functional.Tests/FunctionalTest.cs:line 2728"}
Unhandled exception. Minio.Exceptions.UnexpectedMinioException: MinIO API responded with message=Failed to detect the expected bucket notification event.
   at Minio.Functional.Tests.FunctionalTest.ListenBucketNotificationsAsync_Test1(IMinioClient minio) in /_/Minio.Functional.Tests/FunctionalTest.cs:line 2728
   at Minio.Functional.Tests.FunctionalTest.ListenBucketNotificationsAsync_Test1(IMinioClient minio) in /_/Minio.Functional.Tests/FunctionalTest.cs:line 2778
   at Minio.Functional.Tests.Program.Main(String[] args) in /_/Minio.Functional.Tests/Program.cs:line 115
   at Minio.Functional.Tests.Program.<Main>(String[] args)
/home/runner/work/_temp/ec1[26](https://github.com/minio/minio-dotnet/actions/runs/6099001365/job/16550314502#step:4:27)19f-5506-43d3-9d75-2ab0[31](https://github.com/minio/minio-dotnet/actions/runs/6099001365/job/16550314502#step:4:32)ec00a1.sh: line 8:  1752 Aborted                 (core dumped) dotnet Minio.Functional.Tests/bin/Release/net7.0/Minio.Functional.Tests.dll
Error: Process completed with exit code 1[34](https://github.com/minio/minio-dotnet/actions/runs/6099001365/job/16550314502#step:4:35).
```

**Comment by ebozduman** [comment]
@harshavardhana 

I just ran your recommended command: `wget`:
```
wget --quiet -O /tmp/minio https://dl.min.io/server/minio/release/linux-amd64/minio
```

But I could not reproduce the problem and the file is created correctly in the expected location, `/tmp/minio`
```
$ ll /tmp/minio 
-rw-rw-r-- 1 owner owner 97255424 Oct 15 22:48 /tmp/minio
$
```

I ran the command against `play.min.io`.
Either this issue has been fixed due to some recent changes or I missed a reproduction step.

Could you check it again?

**Comment by minio-trusted** [comment]
This seems to be fixed.
