### ISSUE TITLE
Using .WithStreamData throws "Object reference not set to an instance of an object" when using MinIO 4.x or higher

### ISSUE THREAD

**Issue by cwhfa** [minio/minio-dotnet#876]
Hi, so this might just be me that is stupid but I can't figure out why it's happening.

## Expected Behavior

Expected the file to be uploaded to bucket

## Current Behavior

Exception on `PutObjectAsync`

```
Minio.Exceptions.ConnectionException: MinIO API responded with message=Connection error:Object reference not set to an instance of an object.. Status code=0, response=Object reference not set to an instance of an object., content=
   at Minio.MinioClient.ParseErrorNoContent(ResponseResult response)
   at Minio.MinioClient.ParseError(ResponseResult response)
   at Minio.Handlers.DefaultErrorHandler.Handle(ResponseResult response)
   at Minio.RequestExtensions.HandleIfErrorResponse(IMinioClient minioClient, ResponseResult response, IEnumerable`1 handlers, DateTime startTime)
   at Minio.RequestExtensions.ExecuteTaskCoreAsync(IMinioClient minioClient, IEnumerable`1 errorHandlers, HttpRequestMessageBuilder requestMessageBuilder, Boolean isSts, CancellationToken cancellationToken)
   at Minio.MinioClient.PutObjectSinglePartAsync(PutObjectArgs args, CancellationToken cancellationToken)
   at Minio.MinioClient.PutObjectAsync(PutObjectArgs args, CancellationToken cancellationToken)
   at Program.<Main>$(String[] args) in C:\temp\MinIoTest\MinIoTest\Program.cs:line 22
```

## Steps to Reproduce (for bugs)

1. Use docker-compose.yml to run MinIO
```
version: "3.7"

services:
  minio:
    image: minio/minio:latest
    command: server --console-address ":9001" /data
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./data:/data

volumes:
  data:
```

2. Run code below with MinIO version 6.0.0 as NuGet package reference
```
using System.Text;
using Minio;
using Minio.DataModel.Args;

var minIoClient = new MinioClient()
    .WithEndpoint("localhost:9000")
    .WithCredentials("minioadmin", "minioadmin");

var content = Encoding.UTF8.GetBytes("test");

var bucket = "dev";
var key = "test.html";

using (var stream = new MemoryStream(content))
{
    var request = new PutObjectArgs()
        .WithBucket(bucket)
        .WithObject(key)
        .WithStreamData(stream)
        .WithObjectSize(stream.Length);

    await minIoClient.PutObjectAsync(request);
}
```
3. `PutObjectAsync` should throw an exception

## Context

I was upgrading MinIO from 3.x to 6.x. In 3.x with the same code (Except the fluent changes) it works

## Regression

Yes. Version 4.x and higher

## Your Environment

Version used:
`RELEASE.2023-09-30T07-02-29Z (go1.21.1 linux/amd64)`

Server setup and configuration:
Windows 10
.net core 7

**Comment by klauspost** [comment]
It seems you are missing `.Build()` on your request.
