### ISSUE TITLE
Possible bug in functional tests for signature failure

### ISSUE THREAD

**Issue by harshavardhana** [minio/minio-dotnet#949]
Possible bug in our functional tests

```
{"Name":"minio-dotnet : ObjectVersioningAsync_Test1","Function":"Task RemoveBucketTagsAsync(RemoveBucketTagsArgs args, CancellationToken cancellationToken = default(CancellationToken))","Description":"Tests whether SetVersioningAsync/GetVersioningAsync/RemoveVersioningAsync passes","Args":{"bucketName":"minio-dotnet-example-aleb0h65g5f7lkv","objectName":"minio-dotnet-example-zzjhpxh21w","fileSize":"6291456"},"Duration":80235,"Status":"PASS"}
Unhandled exception. Minio.Exceptions.AuthorizationException: The request signature we calculated does not match the signature you provided. Check your key and signing method.
   at Minio.MinioClient.ParseErrorFromContent(ResponseResult response) in /_/Minio/MinioClient.cs:line 243
   at Minio.MinioClient.ParseError(ResponseResult response) in /_/Minio/MinioClient.cs:line 119
   at Minio.Handlers.DefaultErrorHandler.Handle(ResponseResult response) in /_/Minio/Handlers/DefaultErrorHandler.cs:line 13
   at Minio.RequestExtensions.HandleIfErrorResponse(IMinioClient minioClient, ResponseResult response, IEnumerable`1 handlers, DateTime startTime) in /_/Minio/RequestExtensions.cs:line 370
   at Minio.RequestExtensions.ExecuteTaskCoreAsync(IMinioClient minioClient, IEnumerable`1 errorHandlers, HttpRequestMessageBuilder requestMessageBuilder, Boolean isSts, CancellationToken cancellationToken) in /_/Minio/RequestExtensions.cs:line 136
   at Minio.RequestExtensions.<>c__DisplayClass2_0.<<ExecuteTaskAsync>b__0>d.MoveNext() in /_/Minio/RequestExtensions.cs:line 64
--- End of stack trace from previous location ---
   at Minio.MinioClient.NewMultipartUploadAsync(NewMultipartUploadPutArgs args, CancellationToken cancellationToken) in /_/Minio/ApiEndpoints/ObjectOperations.cs:line 1040
   at Minio.MinioClient.PutObjectAsync(PutObjectArgs args, CancellationToken cancellationToken) in /_/Minio/ApiEndpoints/ObjectOperations.cs:line 611
   at Minio.Functional.Tests.FunctionalTest.ListIncompleteUpload_Test2(IMinioClient minio) in /_/Minio.Functional.Tests/FunctionalTest.cs:line 5837
   at Minio.Functional.Tests.FunctionalTest.ListIncompleteUpload_Test2(IMinioClient minio) in /_/Minio.Functional.Tests/FunctionalTest.cs:line 5865
   at Minio.Helper.Utils.ForEachAsync[TSource](IEnumerable`1 source, Boolean runInParallel, Int32 maxNoOfParallelProcesses) in /_/Minio/Helper/Utils.cs:line 235
   at Minio.Functional.Tests.Program.Main(String[] args) in /_/Minio.Functional.Tests/Program.cs:line 254
   at Minio.Functional.Tests.Program.<Main>(String[] args)
/home/runner/work/_temp/844d191c-98d5-4efd-a020-3cdbc9991103.sh: line 8:  1837 Aborted                 (core dumped) dotnet Minio.Functional.Tests/bin/Release/net7.0/Minio.Functional.Tests.dll
```

**Comment by harshavardhana** [comment]
https://github.com/minio/minio-dotnet/actions/runs/7068415351/job/19242974063

**Comment by ebozduman** [comment]
Looking into it
